### ISSUE TITLE
Mac OS Sierra edits broke the widget.

### ISSUE THREAD

**Issue by Jacobvs** [dionmunk/ubersicht-network-throughput#2]
In the index.coffee and the network.sh files, you have them referencing a widget called "network-usage-bar.widget" but the project files are called "network-throughput." Just wanted to let you know that it broke the widget for me. Otherwise great project, I like it!

**Comment by dionmunk** [comment]
Resolved by https://github.com/dionmunk/ubersicht-network-throughput/commit/bae60f634cd04237af18d70465f3d274913ad50f.
